/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

/**
 *
 * @author PAUL
 */
public class AgregarPago extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPago
     */
    public AgregarPago() {
        initComponents();
    }
    
    public class Tipo_Pago 
    {
        public static String tipoPago = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxTipoPago = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnSeleccionarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("PAGOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 40);

        cbxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matrícula", "Impresos", "Pensiones" }));
        cbxTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPagoActionPerformed(evt);
            }
        });
        jPanel3.add(cbxTipoPago);
        cbxTipoPago.setBounds(20, 70, 150, 22);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Tipo de Pago");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 50, 80, 15);

        btnSeleccionarPago.setBackground(new java.awt.Color(0, 153, 204));
        btnSeleccionarPago.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnSeleccionarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarPago.setText("SELECCIONAR");
        btnSeleccionarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPagoActionPerformed(evt);
            }
        });
        jPanel3.add(btnSeleccionarPago);
        btnSeleccionarPago.setBounds(200, 70, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPagoActionPerformed
        if(cbxTipoPago.getSelectedItem().equals("Matrícula")){
            Tipo_Pago.tipoPago = cbxTipoPago.getSelectedItem().toString();
            TipoMatricula matricula = new TipoMatricula();
            matricula.setVisible(true);
            matricula.setLocationRelativeTo(null);
            this.dispose();
        }
        else if(cbxTipoPago.getSelectedItem().equals("Pensiones")){
            Tipo_Pago.tipoPago = cbxTipoPago.getSelectedItem().toString();
            TipoPensiones pensiones = new TipoPensiones();
            pensiones.setVisible(true);
            pensiones.setLocationRelativeTo(null);
            this.dispose();
        }
        else if(cbxTipoPago.getSelectedItem().equals("Impresos")){
            Tipo_Pago.tipoPago = cbxTipoPago.getSelectedItem().toString();
            TipoImpresos impresos = new TipoImpresos();
            impresos.setVisible(true);
            impresos.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnSeleccionarPagoActionPerformed

    private void cbxTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPagoActionPerformed
        
    }//GEN-LAST:event_cbxTipoPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSeleccionarPago;
    public javax.swing.JComboBox<String> cbxTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
