/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author PAUL
 */
public class AgregarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form AgregarEstudiante
     */
    public AgregarEstudiante() {
        initComponents();
    }

    private int idEstudianteEditar = -1;
    private boolean modoEdicion = false;

    public void setDatosParaEdicion(int idEstudiante, String nombres, String apellidos, String dni, String sexo, String domicilio, String procedencia) {
        this.idEstudianteEditar = idEstudiante;
        tbNombres1.setText(nombres);
        tbApellidos1.setText(apellidos);
        tbDni1.setText(dni);
        cbxSexo1.setSelectedItem(sexo);
        tbDomicilio1.setText(domicilio);
        tbProcedencia1.setText(procedencia);

        btnAgregarRegistroEst.setText("Guardar cambios");
        modoEdicion = true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbDni1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tbProcedencia1 = new javax.swing.JTextField();
        tbDomicilio1 = new javax.swing.JTextField();
        cbxSexo1 = new javax.swing.JComboBox<>();
        btnAgregarRegistroEst = new javax.swing.JButton();
        tbApellidos1 = new javax.swing.JTextField();
        tbNombres1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(526, 269));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Domicilio");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 110, 49, 15);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("I.E de Procedencia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 170, 110, 15);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Sexo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 110, 26, 15);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("ESTUDIANTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 40);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Nombres");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 50, 48, 15);

        tbDni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDni1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbDni1);
        tbDni1.setBounds(390, 70, 110, 22);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("Apellidos");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 50, 49, 15);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("DNI");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 50, 18, 15);

        tbProcedencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProcedencia1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbProcedencia1);
        tbProcedencia1.setBounds(10, 190, 240, 22);

        tbDomicilio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDomicilio1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbDomicilio1);
        tbDomicilio1.setBounds(200, 130, 300, 22);

        cbxSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        getContentPane().add(cbxSexo1);
        cbxSexo1.setBounds(10, 130, 150, 22);

        btnAgregarRegistroEst.setBackground(new java.awt.Color(0, 153, 204));
        btnAgregarRegistroEst.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarRegistroEst.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarRegistroEst.setText("REGISTRAR");
        btnAgregarRegistroEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegistroEstActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarRegistroEst);
        btnAgregarRegistroEst.setBounds(330, 190, 120, 20);

        tbApellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbApellidos1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbApellidos1);
        tbApellidos1.setBounds(200, 70, 150, 22);

        tbNombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombres1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbNombres1);
        tbNombres1.setBounds(10, 70, 150, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDni1ActionPerformed

    private void tbProcedencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProcedencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProcedencia1ActionPerformed

    private void tbDomicilio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDomicilio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDomicilio1ActionPerformed

    private void btnAgregarRegistroEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegistroEstActionPerformed
        if (tbNombres1.getText().trim().isEmpty() || tbApellidos1.getText().trim().isEmpty() || tbDni1.getText().trim().isEmpty() || cbxSexo1.getSelectedItem() == null || tbDomicilio1.getText().trim().isEmpty() || tbProcedencia1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar todos los campos requeridos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String nombres = tbNombres1.getText().trim();
        String apellidos = tbApellidos1.getText().trim();
        String dni = tbDni1.getText().trim();
        String sexo = cbxSexo1.getSelectedItem().toString();
        String domicilio = tbDomicilio1.getText().trim();
        String procedencia = tbProcedencia1.getText().trim();

        Connection conn = null;
        PreparedStatement pst = null;
        RegistrarEstudiante rp = new RegistrarEstudiante();
        
        try{
            conn = ConexionSQL.getConexion();
            
            if(modoEdicion) {
                String sql = "UPDATE tb_estudiante SET nombres = ?, apellidos = ?, dni = ?, sexo = ?, domicilio = ?, IE_procedencia = ? WHERE id = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, nombres);
                pst.setString(2, apellidos);
                pst.setString(3, dni);
                pst.setString(4, sexo);
                pst.setString(5, domicilio);
                pst.setString(6, procedencia);
                pst.setInt(7, idEstudianteEditar);
                
                int filasActualizadas = pst.executeUpdate();
                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Estudiante actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarEstudiantesBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el estudiante.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                String sql = "INSERT INTO tb_estudiante (nombres, apellidos, dni, sexo, domicilio, IE_procedencia) VALUES (?, ?, ?, ?, ?, ?)";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, nombres);
                pst.setString(2, apellidos);
                pst.setString(3, dni);
                pst.setString(4, sexo);
                pst.setString(5, domicilio);
                pst.setString(6, procedencia);

                int filasInsertadas = pst.executeUpdate();
                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(null, "Registro agregado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarEstudiantesBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el registro a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al conectar o insertar en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
            
            }
        }
    }//GEN-LAST:event_btnAgregarRegistroEstActionPerformed

    private void reiniciarFormulario() {
        idEstudianteEditar = -1;
        modoEdicion = false;
        btnAgregarRegistroEst.setText("REGISTRAR");

        tbNombres1.setText("");
        tbApellidos1.setText("");
        tbDni1.setText("");
        cbxSexo1.setSelectedIndex(0);
        tbDomicilio1.setText("");
        tbProcedencia1.setText("");
    }
    
    private void tbApellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbApellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbApellidos1ActionPerformed

    private void tbNombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombres1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarRegistroEst;
    public javax.swing.JComboBox<String> cbxSexo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField tbApellidos1;
    public javax.swing.JTextField tbDni1;
    public javax.swing.JTextField tbDomicilio1;
    public javax.swing.JTextField tbNombres1;
    public javax.swing.JTextField tbProcedencia1;
    // End of variables declaration//GEN-END:variables
}
