/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author PAUL
 */
public class RegistrarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEstudiante
     */
    public RegistrarEstudiante() {
        initComponents();
        tblEstudiantes.setModel(TableEstudiantes.modeloEstudiantes);
        cargarEstudiantesBD(); 
    }
    
    public void cargarEstudiantesBD(){
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try {
            conn = ConexionSQL.getConexion();
            String sql = "SELECT * FROM tb_estudiante";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            TableEstudiantes.modeloEstudiantes.setRowCount(0);
            
            while (rs.next()) {
               TableEstudiantes.modeloEstudiantes.addRow(new Object[]{
                   rs.getString("id"),
                   rs.getString("nombres"),
                   rs.getString("apellidos"),
                   rs.getString("dni"),
                   rs.getString("sexo"),
                   rs.getString("domicilio"),
                   rs.getString("IE_procedencia")
               });
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error al cargar estudiantes: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally{
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                
            }             
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPanelControl2 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnPagos2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAgregarEstudiante = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnBuscarEst = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNombresEst = new javax.swing.JTextField();
        btnApellidosEst = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnDniEst = new javax.swing.JTextField();
        btnEliminar2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCerrarSesion2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(880, 467));

        jPanel1.setMinimumSize(new java.awt.Dimension(880, 541));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 541));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRO DE PAGOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 170, 60);

        btnPanelControl2.setBackground(new java.awt.Color(51, 51, 51));
        btnPanelControl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPanelControl2.setForeground(new java.awt.Color(255, 255, 255));
        btnPanelControl2.setBorder(null);
        btnPanelControl2.setLabel("Panel de Control");
        btnPanelControl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelControl2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPanelControl2);
        btnPanelControl2.setBounds(0, 60, 170, 60);

        jButton17.setBackground(new java.awt.Color(0, 204, 102));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton17.setLabel("Estudiantes");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(0, 120, 170, 130);

        btnPagos2.setBackground(new java.awt.Color(51, 51, 51));
        btnPagos2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPagos2.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos2.setBorder(null);
        btnPagos2.setLabel("Pagos");
        btnPagos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagos2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagos2);
        btnPagos2.setBounds(0, 250, 170, 130);

        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("ESTUDIANTES");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(12, 17, 112, 21);

        jSeparator2.setForeground(new java.awt.Color(0, 204, 102));
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(12, 44, 720, 10);

        btnAgregarEstudiante.setBackground(new java.awt.Color(0, 153, 204));
        btnAgregarEstudiante.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEstudiante.setText("+ AGREGAR ESTUDIANTE");
        btnAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstudianteActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregarEstudiante);
        btnAgregarEstudiante.setBounds(560, 10, 167, 22);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel2.setText("Administrar información de los Estudiantes");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Dni", "Sexo", "Domicilio", "IE de Procedencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(12, 165, 710, 294);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Búsqueda:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(43, 60, 66, 15);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(11, 65, 26, 10);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(115, 65, 610, 10);

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.add(jSeparator4);
        jSeparator4.setBounds(12, 149, 710, 10);

        btnBuscarEst.setBackground(new java.awt.Color(0, 204, 102));
        btnBuscarEst.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnBuscarEst.setText("BUSCAR");
        btnBuscarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarEst);
        btnBuscarEst.setBounds(630, 100, 98, 22);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Nombres");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(11, 81, 48, 15);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Apellidos");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(181, 81, 49, 15);

        btnNombresEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombresEstActionPerformed(evt);
            }
        });
        jPanel5.add(btnNombresEst);
        btnNombresEst.setBounds(11, 108, 137, 22);

        btnApellidosEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApellidosEstActionPerformed(evt);
            }
        });
        jPanel5.add(btnApellidosEst);
        btnApellidosEst.setBounds(181, 108, 137, 22);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("DNI");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(363, 81, 18, 15);

        btnDniEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDniEstActionPerformed(evt);
            }
        });
        jPanel5.add(btnDniEst);
        btnDniEst.setBounds(363, 108, 137, 22);

        btnEliminar2.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnEliminar2.setText("ELIMINAR");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminar2);
        btnEliminar2.setBounds(530, 120, 80, 22);

        btnEditar2.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnEditar2.setText("EDITAR");
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditar2);
        btnEditar2.setBounds(530, 80, 80, 22);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(24, 21, 740, 460);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(170, 60, 790, 480);

        jPanel4.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(170, 0, 790, 60);

        btnCerrarSesion2.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarSesion2.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCerrarSesion2.setLabel("Cerrar Sesión");
        btnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion2);
        btnCerrarSesion2.setBounds(0, 380, 170, 50);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 430, 170, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelControl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelControl2ActionPerformed
        PantallaInicio panelControl = new PantallaInicio();
        panelControl.setVisible(true);
        panelControl.setLocationRelativeTo(null);
        this.dispose();     
    }//GEN-LAST:event_btnPanelControl2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btnPagos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagos2ActionPerformed
        RegistrarPagos registrarPago2 = new RegistrarPagos();
        registrarPago2.setVisible(true);
        registrarPago2.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_btnPagos2ActionPerformed

    private void btnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesion2ActionPerformed

    private void btnNombresEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombresEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNombresEstActionPerformed

    private void btnApellidosEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApellidosEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApellidosEstActionPerformed

    private void btnDniEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDniEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDniEstActionPerformed

    private void btnAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstudianteActionPerformed
        AgregarEstudiante agregarEst2 = new AgregarEstudiante();
        agregarEst2.setVisible(true);
        agregarEst2.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnAgregarEstudianteActionPerformed

    private void btnBuscarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstActionPerformed
        if (btnNombresEst.getText().trim().isEmpty() && btnApellidosEst.getText().trim().isEmpty() && btnDniEst.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese al menos un criterio de búsqueda (Nombre, Apellido o DNI)", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;   
        
        try{
            conn = ConexionSQL.getConexion();
            
            String sql = "SELECT * FROM tb_estudiante WHERE 1=1";
            
            if (!btnNombresEst.getText().trim().isEmpty()) 
            {
                sql += " AND nombres LIKE ?";
            }
            if (!btnApellidosEst.getText().trim().isEmpty()) 
            {
                sql += " AND apellidos LIKE ?";
            }
            if (!btnDniEst.getText().trim().isEmpty()) 
            {
                sql += " AND dni LIKE ?";
            }
            
            pst = conn.prepareStatement(sql);
            
            int index = 1;
            
            if (!btnNombresEst.getText().trim().isEmpty()) 
            {
                pst.setString(index++, "%" + btnNombresEst.getText().trim() + "%");
            }
            if (!btnApellidosEst.getText().trim().isEmpty()) 
            {
                pst.setString(index++, "%" + btnApellidosEst.getText().trim() + "%");
            }
            if (!btnDniEst.getText().trim().isEmpty()) 
            {
                pst.setString(index++, "%" + btnDniEst.getText().trim() + "%");
            }

            rs = pst.executeQuery();
            
            TableEstudiantes.modeloEstudiantes.setRowCount(0);
            
            while (rs.next()) {
                TableEstudiantes.modeloEstudiantes.addRow(new Object[] {
                    rs.getString("id"),
                    rs.getString("nombres"),
                    rs.getString("apellidos"),
                    rs.getString("dni"),
                    rs.getString("sexo"),
                    rs.getString("domicilio"),
                    rs.getString("IE_procedencia")
                });
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error al buscar en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            }catch (SQLException e) {
                
            }
        }
    }//GEN-LAST:event_btnBuscarEstActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        int filaSeleccionada = tblEstudiantes.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un estudiante a eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar a este estudiante?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        
        int id = Integer.parseInt(tblEstudiantes.getValueAt(filaSeleccionada, 0).toString());

        Connection conn = null;
        PreparedStatement pst = null;
        
        try{
            conn = ConexionSQL.getConexion();
            String sql = "DELETE FROM tb_estudiante WHERE id = ?";
            
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            
            int filasAfectadas = pst.executeUpdate();
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "Estudiante eliminado correctamente.");
                TableEstudiantes.modeloEstudiantes.removeRow(filaSeleccionada);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el estudiante a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error al eliminar un estudiante: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                
            }
        }
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        int filaSeleccionada = tblEstudiantes.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un estudiante a editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas editar a este estudiante?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        
        int idEstudiante = Integer.parseInt(tblEstudiantes.getValueAt(filaSeleccionada, 0).toString());
        String nombres = tblEstudiantes.getValueAt(filaSeleccionada, 1).toString();
        String apellidos = tblEstudiantes.getValueAt(filaSeleccionada, 2).toString();
        String dni = tblEstudiantes.getValueAt(filaSeleccionada, 3).toString();
        String sexo = tblEstudiantes.getValueAt(filaSeleccionada, 4).toString();
        String domicilio = tblEstudiantes.getValueAt(filaSeleccionada, 5).toString();
        String procedencia = tblEstudiantes.getValueAt(filaSeleccionada, 6).toString();
        
        AgregarEstudiante formEdicion = new AgregarEstudiante();
        formEdicion.setDatosParaEdicion(idEstudiante, nombres, apellidos, dni, sexo, domicilio, procedencia);
        formEdicion.setVisible(true);
    }//GEN-LAST:event_btnEditar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarEstudiante;
    public javax.swing.JTextField btnApellidosEst;
    public javax.swing.JButton btnBuscarEst;
    public javax.swing.JButton btnCerrarSesion2;
    public javax.swing.JTextField btnDniEst;
    public javax.swing.JButton btnEditar2;
    public javax.swing.JButton btnEliminar2;
    public javax.swing.JTextField btnNombresEst;
    public javax.swing.JButton btnPagos2;
    public javax.swing.JButton btnPanelControl2;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTable tblEstudiantes;
    // End of variables declaration//GEN-END:variables
}
