/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author PAUL
 */
public class RegistrarPagos extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPagos
     */
    public RegistrarPagos() {
        initComponents();
        tblPagos.setModel(TablePagos.modeloPagos);
        cargarPagosBD(); 
    }
    
    public void cargarPagosBD(){
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try {
            conn = ConexionSQL.getConexion();
            String sql = "SELECT * FROM tb_pagos";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            TablePagos.modeloPagos.setRowCount(0);
            
            while (rs.next()) {
               TablePagos.modeloPagos.addRow(new Object[]{
                    rs.getString("id_pagos"),
                    rs.getString("dni_estudiante"),
                    rs.getString("mes"),
                    rs.getString("saldo"),
                    rs.getString("fecha"),
                    rs.getString("num_recibo"),
                    rs.getString("entidad_financiera"),
                    rs.getString("tipo_pago")
                });
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error al cargar pagos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally{
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                
            }             
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnPanelControl3 = new javax.swing.JButton();
        btnEstudiantes3 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btnCerrarSesion3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAgregarPago = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnBuscarPagos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbDniPagos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateFechaPagos = new javax.swing.JFormattedTextField();
        cbxTipoPago = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRO DE PAGOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 170, 60);

        jPanel4.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(170, 0, 780, 60);

        btnPanelControl3.setBackground(new java.awt.Color(51, 51, 51));
        btnPanelControl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPanelControl3.setForeground(new java.awt.Color(255, 255, 255));
        btnPanelControl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPanelControl3.setLabel("Panel de Control");
        btnPanelControl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelControl3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPanelControl3);
        btnPanelControl3.setBounds(0, 60, 170, 60);

        btnEstudiantes3.setBackground(new java.awt.Color(51, 51, 51));
        btnEstudiantes3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEstudiantes3.setForeground(new java.awt.Color(255, 255, 255));
        btnEstudiantes3.setBorder(null);
        btnEstudiantes3.setLabel("Estudiantes");
        btnEstudiantes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantes3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstudiantes3);
        btnEstudiantes3.setBounds(0, 120, 170, 130);

        jButton18.setBackground(new java.awt.Color(0, 204, 102));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton18.setLabel("Pagos");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(0, 250, 170, 130);

        btnCerrarSesion3.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarSesion3.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion3.setBorder(null);
        btnCerrarSesion3.setLabel("Cerrar Sesión");
        btnCerrarSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion3);
        btnCerrarSesion3.setBounds(0, 380, 170, 50);

        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("PAGOS");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(12, 17, 56, 21);

        jSeparator2.setForeground(new java.awt.Color(0, 204, 102));
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(12, 44, 710, 10);

        btnAgregarPago.setBackground(new java.awt.Color(0, 153, 204));
        btnAgregarPago.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPago.setText("+ AGREGAR PAGO");
        btnAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPagoActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregarPago);
        btnAgregarPago.setBounds(590, 10, 129, 22);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel2.setText("Administrar información de los Pagos");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Dni", "Mes", "Saldo", "Fecha", "N° de Recibo", "Entidad Financiera", "Tipo de Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPagos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(12, 165, 700, 294);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Búsqueda:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(43, 60, 66, 15);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(11, 65, 26, 10);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(115, 65, 600, 10);

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.add(jSeparator4);
        jSeparator4.setBounds(12, 149, 700, 10);

        btnBuscarPagos.setBackground(new java.awt.Color(0, 204, 102));
        btnBuscarPagos.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnBuscarPagos.setText("BUSCAR");
        btnBuscarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPagosActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarPagos);
        btnBuscarPagos.setBounds(620, 100, 98, 22);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("DNI");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(11, 81, 18, 15);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Tipo de Pago");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(181, 81, 72, 15);

        tbDniPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDniPagosActionPerformed(evt);
            }
        });
        jPanel5.add(tbDniPagos);
        tbDniPagos.setBounds(11, 108, 137, 22);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("Fecha");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(353, 81, 33, 15);

        dateFechaPagos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateFechaPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dateFechaPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFechaPagosActionPerformed(evt);
            }
        });
        jPanel5.add(dateFechaPagos);
        dateFechaPagos.setBounds(353, 108, 129, 22);

        cbxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matrícula", "Impresos", "Pensiones" }));
        cbxTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPagoActionPerformed(evt);
            }
        });
        jPanel5.add(cbxTipoPago);
        cbxTipoPago.setBounds(181, 108, 137, 22);

        btnEditar.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditar);
        btnEditar.setBounds(520, 80, 80, 22);

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminar);
        btnEliminar.setBounds(520, 120, 80, 22);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(24, 21, 730, 460);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(170, 60, 780, 480);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 430, 170, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelControl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelControl3ActionPerformed
        PantallaInicio panelControl3 = new PantallaInicio();
        panelControl3.setVisible(true);
        panelControl3.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPanelControl3ActionPerformed

    private void btnEstudiantes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantes3ActionPerformed
        RegistrarEstudiante registrarEst3 = new RegistrarEstudiante();
        registrarEst3.setVisible(true);
        registrarEst3.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnEstudiantes3ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void btnCerrarSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesion3ActionPerformed

    private void tbDniPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDniPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDniPagosActionPerformed

    private void btnAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPagoActionPerformed
        AgregarPago agregarPago2 = new AgregarPago();
        agregarPago2.setVisible(true);
        agregarPago2.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarPagoActionPerformed

    private void dateFechaPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFechaPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFechaPagosActionPerformed

    private void btnBuscarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPagosActionPerformed
        if (tbDniPagos.getText().trim().isEmpty() && cbxTipoPago.getSelectedItem() == null && dateFechaPagos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese al menos un criterio de búsqueda (DNI, Tipo de pago o Fecha)", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try {
            conn = ConexionSQL.getConexion();
            String sql = "SELECT * FROM tb_pagos WHERE 1=1";

            if (!tbDniPagos.getText().trim().isEmpty()) {
                sql += " AND dni_estudiante LIKE ?";
            }
            if (cbxTipoPago.getSelectedItem() != null && !cbxTipoPago.getSelectedItem().toString().equalsIgnoreCase("Todos")) {
                sql += " AND tipo_pago LIKE ?";
            }
            if (!dateFechaPagos.getText().trim().isEmpty()) {
                sql += " AND fecha = ?";
            }

            pst = conn.prepareStatement(sql);
            
            int index = 1;
            
            if (!tbDniPagos.getText().trim().isEmpty()) {
                pst.setString(index++, "%" + tbDniPagos.getText().trim() + "%");
            }
            if (cbxTipoPago.getSelectedItem() != null && !cbxTipoPago.getSelectedItem().toString().equalsIgnoreCase("Todos")) {
                pst.setString(index++, cbxTipoPago.getSelectedItem().toString());
            }
            if (!dateFechaPagos.getText().trim().isEmpty()) {
                pst.setString(index++, dateFechaPagos.getText().trim());
            }
            rs = pst.executeQuery();
            TablePagos.modeloPagos.setRowCount(0);
            
            while (rs.next()) {
                TablePagos.modeloPagos.addRow(new Object[] {
                    rs.getString("id_pagos"),
                    rs.getString("dni_estudiante"),
                    rs.getString("mes"),
                    rs.getDouble("saldo"),
                    rs.getString("fecha"),
                    rs.getString("num_recibo"),
                    rs.getString("entidad_financiera"),
                    rs.getString("tipo_pago")
                });
            }         
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error al buscar pagos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
        finally{
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                    
            }           
        }
    }//GEN-LAST:event_btnBuscarPagosActionPerformed

    private void cbxTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPagoActionPerformed

    }//GEN-LAST:event_cbxTipoPagoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblPagos.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un pago a eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar este pago?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        
        int idPago = Integer.parseInt(tblPagos.getValueAt(filaSeleccionada, 0).toString());

        Connection conn = null;
        PreparedStatement pst = null;
        
        try{
            conn = ConexionSQL.getConexion();
            String sql = "DELETE FROM tb_pagos WHERE id_pagos = ?";
            
            pst = conn.prepareStatement(sql);
            pst.setInt(1, idPago);
            
            int filasAfectadas = pst.executeUpdate();
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "Pago eliminado correctamente.");
                TablePagos.modeloPagos.removeRow(filaSeleccionada);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el pago a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error al eliminar el pago: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int filaSeleccionada = tblPagos.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un pago a editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas editar este pago?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        
        int idPago = Integer.parseInt(tblPagos.getValueAt(filaSeleccionada, 0).toString());
        String dni = tblPagos.getValueAt(filaSeleccionada, 1).toString();
        String mes = tblPagos.getValueAt(filaSeleccionada, 2) != null ? tblPagos.getValueAt(filaSeleccionada, 2).toString() : "";
        double saldo = Double.parseDouble(tblPagos.getValueAt(filaSeleccionada, 3).toString());
        String fecha = tblPagos.getValueAt(filaSeleccionada, 4).toString();
        String numRecibo = tblPagos.getValueAt(filaSeleccionada, 5).toString();
        String entidadFinanciera = tblPagos.getValueAt(filaSeleccionada, 6).toString();
        String tipoPago = tblPagos.getValueAt(filaSeleccionada, 7).toString();
        
        if (tipoPago.equalsIgnoreCase("Impresos")) {
            TipoImpresos impFrame = new TipoImpresos();
            impFrame.setDatosParaEdicion(idPago, dni, saldo, fecha, numRecibo, entidadFinanciera);
            impFrame.setVisible(true);
        } 
        else if (tipoPago.equalsIgnoreCase("Matrícula")) {
            TipoMatricula matFrame = new TipoMatricula();
            matFrame.setDatosParaEdicion(idPago, dni, saldo, fecha, numRecibo, entidadFinanciera);
            matFrame.setVisible(true);
        } 
        else if (tipoPago.equalsIgnoreCase("Pensiones")) {
            TipoPensiones penFrame = new TipoPensiones();
            penFrame.setDatosParaEdicion(idPago, dni, mes, saldo, fecha, numRecibo, entidadFinanciera);
            penFrame.setVisible(true);
        } 
        else {
            JOptionPane.showMessageDialog(null, "Tipo de pago no reconocido: " + tipoPago);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarPago;
    public javax.swing.JButton btnBuscarPagos;
    public javax.swing.JButton btnCerrarSesion3;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEstudiantes3;
    public javax.swing.JButton btnPanelControl3;
    public javax.swing.JComboBox<String> cbxTipoPago;
    public javax.swing.JFormattedTextField dateFechaPagos;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField tbDniPagos;
    public javax.swing.JTable tblPagos;
    // End of variables declaration//GEN-END:variables
}
