/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
/**
 *
 * @author PAUL
 */
public class TipoPensiones extends javax.swing.JFrame {

    /**
     * Creates new form TipoPensiones
     */
    public TipoPensiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarPen = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tbDni2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbxMes2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tbNumRecibo2 = new javax.swing.JTextField();
        tbEntFinanciera2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tbSaldo2 = new javax.swing.JTextField();
        dateFecha2 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(416, 282));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 282));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("PENSIONES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 40);

        btnRegistrarPen.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistrarPen.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnRegistrarPen.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPen.setText("REGISTRAR");
        btnRegistrarPen.setToolTipText("");
        btnRegistrarPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPenActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPen);
        btnRegistrarPen.setBounds(200, 190, 150, 20);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("Mes");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 50, 30, 15);

        tbDni2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDni2ActionPerformed(evt);
            }
        });
        jPanel1.add(tbDni2);
        tbDni2.setBounds(10, 70, 110, 22);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("DNI");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 50, 18, 15);

        cbxMes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(cbxMes2);
        cbxMes2.setBounds(140, 70, 110, 22);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText("Saldo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 50, 29, 15);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 110, 40, 15);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel12.setText("N° de Recibo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(140, 110, 80, 15);

        tbNumRecibo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNumRecibo2ActionPerformed(evt);
            }
        });
        jPanel1.add(tbNumRecibo2);
        tbNumRecibo2.setBounds(140, 130, 240, 22);

        tbEntFinanciera2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEntFinanciera2ActionPerformed(evt);
            }
        });
        jPanel1.add(tbEntFinanciera2);
        tbEntFinanciera2.setBounds(10, 190, 130, 22);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel13.setText("Entidad Financiera");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 170, 110, 15);

        tbSaldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSaldo2ActionPerformed(evt);
            }
        });
        jPanel1.add(tbSaldo2);
        tbSaldo2.setBounds(270, 70, 110, 22);

        dateFecha2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateFecha2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(dateFecha2);
        dateFecha2.setBounds(10, 130, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int idPagoEditar = -1;
    private boolean modoEdicion = false;

    public void setDatosParaEdicion(int idPago, String dni, String mes, double saldo, String fecha, String numRecibo, String entidad) {
        this.idPagoEditar = idPago;
        tbDni2.setText(dni);
        cbxMes2.setSelectedItem(mes);
        tbSaldo2.setText(String.valueOf(saldo));
        dateFecha2.setText(fecha);
        tbNumRecibo2.setText(numRecibo);
        tbEntFinanciera2.setText(entidad);
        
        btnRegistrarPen.setText("Guardar cambios");
        modoEdicion = true;
    }
    
    private void btnRegistrarPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPenActionPerformed
        if (tbDni2.getText().trim().isEmpty() || cbxMes2.getSelectedItem() == null || tbSaldo2.getText().trim().isEmpty() || dateFecha2.getText().trim().isEmpty() || tbNumRecibo2.getText().trim().isEmpty() || tbEntFinanciera2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Completar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String dni = tbDni2.getText().trim();
        String mes = cbxMes2.getSelectedItem().toString();
        double saldo = Double.parseDouble(tbSaldo2.getText().trim());
        String fecha = dateFecha2.getText().trim();
        String numRecibo = tbNumRecibo2.getText().trim();
        String entidad = tbEntFinanciera2.getText().trim();
        
        Connection conn = null;
        PreparedStatement pst = null;
        RegistrarPagos rp = new RegistrarPagos();
        
        try{
            conn = ConexionSQL.getConexion();
            
            if (modoEdicion) {

                String sql = "UPDATE tb_pagos SET dni_estudiante = ?, mes = ?, saldo = ?, fecha = ?, num_recibo = ?, entidad_financiera = ? WHERE id_pagos = ?";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, dni);
                pst.setString(2, mes);
                pst.setDouble(3, saldo);
                pst.setString(4, fecha);
                pst.setString(5, numRecibo);
                pst.setString(6, entidad);
                pst.setInt(7, idPagoEditar);
            
                int filasActualizadas = pst.executeUpdate();
                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Pago actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarPagosBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el pago.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                TablePagos.modeloPagos.addRow(new Object[]{
                    dni, mes, saldo, fecha, numRecibo, entidad, AgregarPago.Tipo_Pago.tipoPago
                });
                
                String sql = "INSERT INTO tb_pagos (dni_estudiante, mes, saldo, fecha, num_recibo, entidad_financiera, tipo_pago) VALUES (?, ?, ?, ?, ?, ?, ?)";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, dni);
                pst.setString(2, mes);
                pst.setDouble(3, saldo);
                pst.setString(4, fecha);
                pst.setString(5, numRecibo);
                pst.setString(6, entidad);
                pst.setString(7, AgregarPago.Tipo_Pago.tipoPago);
                
                int filasInsertadas = pst.executeUpdate();
                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(this, "Pago registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarPagosBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el registro a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }             
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } 
            catch (SQLException e) {
            
            }
        }
    }//GEN-LAST:event_btnRegistrarPenActionPerformed

    private void reiniciarFormulario() {
        idPagoEditar = -1;
        modoEdicion = false;
        btnRegistrarPen.setText("REGISTRAR");

        tbDni2.setText("");
        cbxMes2.setSelectedIndex(0);
        tbSaldo2.setText("");
        dateFecha2.setText("");
        tbNumRecibo2.setText("");
        tbEntFinanciera2.setText("");
    }
    
    private void tbDni2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDni2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDni2ActionPerformed

    private void tbNumRecibo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNumRecibo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNumRecibo2ActionPerformed

    private void tbEntFinanciera2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEntFinanciera2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEntFinanciera2ActionPerformed

    private void tbSaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSaldo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSaldo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoPensiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoPensiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoPensiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPensiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoPensiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarPen;
    public javax.swing.JComboBox<String> cbxMes2;
    public javax.swing.JFormattedTextField dateFecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField tbDni2;
    public javax.swing.JTextField tbEntFinanciera2;
    public javax.swing.JTextField tbNumRecibo2;
    public javax.swing.JTextField tbSaldo2;
    // End of variables declaration//GEN-END:variables
}
