/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author PAUL
 */
public class TipoImpresos extends javax.swing.JFrame {

    /**
     * Creates new form TipoImpresos
     */
    public TipoImpresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarImpre = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tbDni3 = new javax.swing.JTextField();
        tbSaldo3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateFecha3 = new javax.swing.JFormattedTextField();
        tbEntFinanciera3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tbNumRecibo3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("IMPRESOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 40);

        btnRegistrarImpre.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistrarImpre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnRegistrarImpre.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarImpre.setText("REGISTRAR");
        btnRegistrarImpre.setToolTipText("");
        btnRegistrarImpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarImpreActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarImpre);
        btnRegistrarImpre.setBounds(130, 180, 140, 20);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("DNI");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 50, 18, 15);

        tbDni3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDni3ActionPerformed(evt);
            }
        });
        jPanel1.add(tbDni3);
        tbDni3.setBounds(10, 70, 110, 22);

        tbSaldo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSaldo3ActionPerformed(evt);
            }
        });
        jPanel1.add(tbSaldo3);
        tbSaldo3.setBounds(140, 70, 110, 22);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText("Saldo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(140, 50, 29, 15);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 50, 40, 15);

        dateFecha3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateFecha3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dateFecha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFecha3ActionPerformed(evt);
            }
        });
        jPanel1.add(dateFecha3);
        dateFecha3.setBounds(270, 70, 110, 20);

        tbEntFinanciera3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEntFinanciera3ActionPerformed(evt);
            }
        });
        jPanel1.add(tbEntFinanciera3);
        tbEntFinanciera3.setBounds(250, 130, 130, 22);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Entidad Financiera");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 110, 120, 15);

        tbNumRecibo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNumRecibo3ActionPerformed(evt);
            }
        });
        jPanel1.add(tbNumRecibo3);
        tbNumRecibo3.setBounds(10, 130, 220, 22);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel12.setText("N° de Recibo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 110, 80, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int idPagoEditar = -1;
    private boolean modoEdicion = false;

    public void setDatosParaEdicion(int idPago, String dni, double saldo, String fecha, String numRecibo, String entidad) {
        this.idPagoEditar = idPago;
        tbDni3.setText(dni);
        tbSaldo3.setText(String.valueOf(saldo));
        dateFecha3.setText(fecha);
        tbNumRecibo3.setText(numRecibo);
        tbEntFinanciera3.setText(entidad);
        
        btnRegistrarImpre.setText("Guardar cambios");
        modoEdicion = true;
    }
    
    private void btnRegistrarImpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarImpreActionPerformed
        if (tbDni3.getText().trim().isEmpty() || tbSaldo3.getText().trim().isEmpty() || dateFecha3.getText().trim().isEmpty() || tbNumRecibo3.getText().trim().isEmpty() || tbEntFinanciera3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String dni = tbDni3.getText().trim();
        String mes = "-"; 
        double saldo = Double.parseDouble(tbSaldo3.getText().trim());
        String fecha = dateFecha3.getText().trim();
        String numRecibo = tbNumRecibo3.getText().trim();
        String entidad = tbEntFinanciera3.getText().trim();
        
        Connection conn = null;
        PreparedStatement pst = null;
        RegistrarPagos rp = new RegistrarPagos();
        
        try{
            conn = ConexionSQL.getConexion();
            
            if (modoEdicion) {

                String sql = "UPDATE tb_pagos SET dni_estudiante = ?, mes = ?, saldo = ?, fecha = ?, num_recibo = ?, entidad_financiera = ? WHERE id_pagos = ?";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, dni);
                pst.setString(2, mes);
                pst.setDouble(3, saldo);
                pst.setString(4, fecha);
                pst.setString(5, numRecibo);
                pst.setString(6, entidad);
                pst.setInt(7, idPagoEditar);
            
                int filasActualizadas = pst.executeUpdate();
                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Pago actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarPagosBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el pago.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                TablePagos.modeloPagos.addRow(new Object[]{
                    dni, mes, saldo, fecha, numRecibo, entidad, AgregarPago.Tipo_Pago.tipoPago
                });
                
                String sql = "INSERT INTO tb_pagos (dni_estudiante, mes, saldo, fecha, num_recibo, entidad_financiera, tipo_pago) VALUES (?, ?, ?, ?, ?, ?, ?)";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, dni);
                pst.setString(2, mes);
                pst.setDouble(3, saldo);
                pst.setString(4, fecha);
                pst.setString(5, numRecibo);
                pst.setString(6, entidad);
                pst.setString(7, AgregarPago.Tipo_Pago.tipoPago);
                
                int filasInsertadas = pst.executeUpdate();
                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(this, "Pago registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarPagosBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el registro a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }             
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } 
            catch (SQLException e) {
            
            }
        }
    }//GEN-LAST:event_btnRegistrarImpreActionPerformed

        private void reiniciarFormulario() {
            idPagoEditar = -1;
            modoEdicion = false;
            btnRegistrarImpre.setText("REGISTRAR");

            tbDni3.setText("");
            tbSaldo3.setText("");
            dateFecha3.setText("");
            tbNumRecibo3.setText("");
            tbEntFinanciera3.setText("");
        }

    private void tbDni3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDni3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDni3ActionPerformed

    private void tbSaldo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSaldo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSaldo3ActionPerformed

    private void dateFecha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFecha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFecha3ActionPerformed

    private void tbEntFinanciera3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEntFinanciera3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEntFinanciera3ActionPerformed

    private void tbNumRecibo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNumRecibo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNumRecibo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoImpresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoImpresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoImpresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoImpresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoImpresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarImpre;
    public javax.swing.JFormattedTextField dateFecha3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField tbDni3;
    public javax.swing.JTextField tbEntFinanciera3;
    public javax.swing.JTextField tbNumRecibo3;
    public javax.swing.JTextField tbSaldo3;
    // End of variables declaration//GEN-END:variables
}
