/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author PAUL
 */
public class TipoMatricula extends javax.swing.JFrame {

    /**
     * Creates new form TipoMatricula
     */
    public TipoMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbDni4 = new javax.swing.JTextField();
        tbEntFinanciera4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateFecha4 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        tbSaldo4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tbNumRecibo4 = new javax.swing.JTextField();
        btnMatricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("MATRÍCULA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 40);

        tbDni4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDni4ActionPerformed(evt);
            }
        });
        jPanel1.add(tbDni4);
        tbDni4.setBounds(10, 70, 110, 22);

        tbEntFinanciera4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEntFinanciera4ActionPerformed(evt);
            }
        });
        jPanel1.add(tbEntFinanciera4);
        tbEntFinanciera4.setBounds(240, 130, 140, 22);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 50, 40, 15);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("DNI");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 50, 18, 15);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Entidad Financiera");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(240, 110, 110, 15);

        dateFecha4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateFecha4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dateFecha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFecha4ActionPerformed(evt);
            }
        });
        jPanel1.add(dateFecha4);
        dateFecha4.setBounds(270, 70, 110, 20);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText("Saldo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(140, 50, 29, 15);

        tbSaldo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSaldo4ActionPerformed(evt);
            }
        });
        jPanel1.add(tbSaldo4);
        tbSaldo4.setBounds(140, 70, 110, 22);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel12.setText("N° de Recibo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 110, 80, 15);

        tbNumRecibo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNumRecibo4ActionPerformed(evt);
            }
        });
        jPanel1.add(tbNumRecibo4);
        tbNumRecibo4.setBounds(10, 130, 200, 22);

        btnMatricular.setBackground(new java.awt.Color(0, 153, 204));
        btnMatricular.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnMatricular.setForeground(new java.awt.Color(255, 255, 255));
        btnMatricular.setText("MATRICULAR");
        btnMatricular.setToolTipText("");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        jPanel1.add(btnMatricular);
        btnMatricular.setBounds(130, 180, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDni4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDni4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDni4ActionPerformed

    private void tbEntFinanciera4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEntFinanciera4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEntFinanciera4ActionPerformed

    private void dateFecha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFecha4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFecha4ActionPerformed

    private void tbSaldo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSaldo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSaldo4ActionPerformed

    private void tbNumRecibo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNumRecibo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNumRecibo4ActionPerformed

    private int idPagoEditar = -1;
    private boolean modoEdicion = false;

    public void setDatosParaEdicion(int idPago, String dni, double saldo, String fecha, String numRecibo, String entidad) {
        this.idPagoEditar = idPago;
        tbDni4.setText(dni);
        tbSaldo4.setText(String.valueOf(saldo));
        dateFecha4.setText(fecha);
        tbNumRecibo4.setText(numRecibo);
        tbEntFinanciera4.setText(entidad);
        
        btnMatricular.setText("Guardar cambios");
        modoEdicion = true;
    }
    
    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
        if (tbDni4.getText().trim().isEmpty() || tbSaldo4.getText().trim().isEmpty() || dateFecha4.getText().trim().isEmpty() || tbNumRecibo4.getText().trim().isEmpty() || tbEntFinanciera4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String dni = tbDni4.getText().trim();
        String mes = "-";
        double saldo = Double.parseDouble(tbSaldo4.getText().trim());
        String fecha = dateFecha4.getText().trim();
        String numRecibo = tbNumRecibo4.getText().trim();
        String entidad = tbEntFinanciera4.getText().trim();
        
        Connection conn = null;
        PreparedStatement pst = null;
        RegistrarPagos rp = new RegistrarPagos();
        
        try{
            conn = ConexionSQL.getConexion();
            
            if (modoEdicion) {

                String sql = "UPDATE tb_pagos SET dni_estudiante = ?, mes = ?, saldo = ?, fecha = ?, num_recibo = ?, entidad_financiera = ? WHERE id_pagos = ?";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, dni);
                pst.setString(2, mes);
                pst.setDouble(3, saldo);
                pst.setString(4, fecha);
                pst.setString(5, numRecibo);
                pst.setString(6, entidad);
                pst.setInt(7, idPagoEditar);
            
                int filasActualizadas = pst.executeUpdate();
                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Pago actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarPagosBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el pago.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                TablePagos.modeloPagos.addRow(new Object[]{
                    dni, mes, saldo, fecha, numRecibo, entidad, AgregarPago.Tipo_Pago.tipoPago
                });
                
                String sql = "INSERT INTO tb_pagos (dni_estudiante, mes, saldo, fecha, num_recibo, entidad_financiera, tipo_pago) VALUES (?, ?, ?, ?, ?, ?, ?)";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1, dni);
                pst.setString(2, mes);
                pst.setDouble(3, saldo);
                pst.setString(4, fecha);
                pst.setString(5, numRecibo);
                pst.setString(6, entidad);
                pst.setString(7, AgregarPago.Tipo_Pago.tipoPago);
                
                int filasInsertadas = pst.executeUpdate();
                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(this, "Pago registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    rp.cargarPagosBD();
                    reiniciarFormulario();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el registro a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }             
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } 
            catch (SQLException e) {
            
            }
        }
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void reiniciarFormulario() {
        idPagoEditar = -1;
        modoEdicion = false;
        btnMatricular.setText("REGISTRAR");

        tbDni4.setText("");
        tbSaldo4.setText("");
        dateFecha4.setText("");
        tbNumRecibo4.setText("");
        tbEntFinanciera4.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMatricular;
    public javax.swing.JFormattedTextField dateFecha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField tbDni4;
    public javax.swing.JTextField tbEntFinanciera4;
    public javax.swing.JTextField tbNumRecibo4;
    public javax.swing.JTextField tbSaldo4;
    // End of variables declaration//GEN-END:variables
}
